version: '3.4'

services:
  # DATA ENGINEERING MODULE
  ## Reimplement this section if you're taking the data engineering test!
  operational-db:
    image: postgres:13
    container_name: operational-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "companydata"]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=companydata
    volumes:
      - ./modules/de/db_admin/setup_users.sql:/docker-entrypoint-initdb.d/setup_users.sql

  airflow:
    build:
      context: ./modules/de/docker
    container_name: airflow
    ports:
      - "8082:8080"
    depends_on:
      operational-db:
        condition: service_healthy
    environment:
      - ADMIN_DB_HOST=operational-db
      - ADMIN_DB_PORT=5432
      - ADMIN_DB_NAME=companydata
      - ADMIN_DB_USER=admin
      - ADMIN_DB_PASSWORD=admin
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@operational-db:5432/companydata
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW_HOME=/opt/airflow
    volumes:
      - ./modules/de/dags:/opt/airflow/dags

  # DATA SCIENCE MODULE
  ## Reimplement this section if you're taking the data science test!
  model-training:
    build:
      context: ./modules  # need this context in order to be able to copy the MLE nodule to the Docker image
      dockerfile: ./ds/docker/Dockerfile
    environment:
      - DS_DB_USER=ds_user
      - DS_DB_PASSWORD=ds_user
      - DB_HOSTNAME=operational-db
      - DB_PORT=5432
    depends_on:
      - operational-db
    volumes:
      - ./modules/ds/models/:/models
