version: '3.4'

services:
  # DATA ENGINEERING MODULE
  ## Reimplement this section if you're taking the data engineering test!
  operational-db:
    image: postgres:13
    container_name: operational-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./modules/de/db_admin/setup_users.sql:/docker-entrypoint-initdb.d/setup_users.sql

  airflow:
    build:
      context: ./modules/de/docker
    container_name: airflow
    ports:
      - "8082:8080"
    environment:
      - ADMIN_DB_HOST=${ADMIN_DB_HOST:-operational-db}
      - ADMIN_DB_PORT=${ADMIN_DB_PORT:-5432}
      - ADMIN_DB_NAME=${ADMIN_DB_NAME}
      - ADMIN_DB_USER=${ADMIN_DB_USER}
      - ADMIN_DB_PASSWORD=${ADMIN_DB_PASSWORD}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW_ADMIN_USERNAME=${AIRFLOW_ADMIN_USERNAME}
      - AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
      - AIRFLOW_ADMIN_FIRSTNAME=${AIRFLOW_ADMIN_FIRSTNAME:-Air}
      - AIRFLOW_ADMIN_LASTNAME=${AIRFLOW_ADMIN_LASTNAME:-Flow}
      - AIRFLOW_ADMIN_EMAIL=${AIRFLOW_ADMIN_EMAIL:-airflow@example.com}
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW_HOME=/opt/airflow
    volumes:
      - ./modules/de/dags:/opt/airflow/dags

  # DATA SCIENCE MODULE
  ## Reimplement this section if you're taking the data science test!
  model-training:
    build:
      context: ./modules  # need this context in order to be able to copy the MLE nodule to the Docker image
      dockerfile: ./ds/docker/Dockerfile
    environment:
      - DS_DB_USER=${DS_DB_USER}
      - DS_DB_PASSWORD=${DS_DB_PASSWORD}
      - DB_HOSTNAME=operational-db
      - DB_PORT=5432
    volumes:
      - ./modules/ds/models/:/models
