[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ds_package"
version = "1.0"
authors = [
  { name="Fred", email="Fred@example.com" },
]
description = "Data Science Package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9,<3.10"
dependencies = [
  "numpy<2",
  "pandas==1.4.4",
  "matplotlib==3.5.3",
  "sqlalchemy==1.4.41",
  "psycopg2-binary==2.9.3",
  "auto-sklearn==0.14.7",
]
